# Makefile for $(corelib)/progs/robotics 
#
# Authors: Cong Wang, Yi-Jen Chiang, Chee Yap (March 2012)
# 
# Since Core Library 2.1 (March 2012)
# 	$Id: $

include ../Make.options

default:
	-@echo "This compile may fail if you do not have GLUT libraries"
	-${MAKE} -C 2d-disc default

test: 

localtest: 
	-${MAKE} -C 2d-disc test

moretest:

clean:
	-${MAKE} -C 2d-disc clean

veryclean:
	-${MAKE} -C 2d-disc veryclean
