
realMini:
	cp ../frisco/chebyshev20.pol .
	cp ../frisco/chrma22.pol .
	cp ../frisco/chrmc23.pol .
	cp ../frisco/hermite20.pol .
	cp ../frisco/laguerre20.pol .
	cp ../frisco/laguerre40.pol .
	cp ../frisco/laguerre80.pol .
	cp ../frisco/wilk20.pol .
	cp ../frisco/wilk40.pol .
	cp ../frisco/wilk80.pol .
	cp ../frisco/nroots50.pol .
	cp ../frisco/nroots100.pol .
